### ISSUE TITLE
pip install -e . Encounter problems

### ISSUE THREAD

**Issue by MAI-KOKO** [qcraftai/pillarnext#17]
root@453cd795ecb9:/home/pillarnext# pip install -e .
Obtaining file:///home/pillarnext
Installing collected packages: det3d
  Running setup.py develop for det3d
    ERROR: Command errored out with exit status 1:
     command: /opt/conda/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/pillarnext/setup.py'"'"'; __file__='"'"'/home/pillarnext/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: /home/pillarnext/
    Complete output (56 lines):
    No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
    running develop
    running egg_info
    writing det3d.egg-info/PKG-INFO
    writing dependency_links to det3d.egg-info/dependency_links.txt
    writing top-level names to det3d.egg-info/top_level.txt
    reading manifest file 'det3d.egg-info/SOURCES.txt'
    adding license file 'LICENSE'
    writing manifest file 'det3d.egg-info/SOURCES.txt'
    running build_ext
    building 'det3d.core.iou3d_nms.iou3d_nms_cuda' extension
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/pillarnext/setup.py", line 18, in <module>
        setup(
      File "/opt/conda/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/opt/conda/lib/python3.9/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/opt/conda/lib/python3.9/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/opt/conda/lib/python3.9/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/opt/conda/lib/python3.9/site-packages/setuptools/command/develop.py", line 34, in run
        self.install_for_development()
      File "/opt/conda/lib/python3.9/site-packages/setuptools/command/develop.py", line 114, in install_for_development
        self.run_command('build_ext')
      File "/opt/conda/lib/python3.9/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/opt/conda/lib/python3.9/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/opt/conda/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 79, in run
        _build_ext.run(self)
      File "/opt/conda/lib/python3.9/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
        _build_ext.build_ext.run(self)
      File "/opt/conda/lib/python3.9/distutils/command/build_ext.py", line 340, in run
        self.build_extensions()
      File "/opt/conda/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 843, in build_extensions
        build_ext.build_extensions(self)
      File "/opt/conda/lib/python3.9/site-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
        _build_ext.build_ext.build_extensions(self)
      File "/opt/conda/lib/python3.9/distutils/command/build_ext.py", line 449, in build_extensions
        self._build_extensions_serial()
      File "/opt/conda/lib/python3.9/distutils/command/build_ext.py", line 474, in _build_extensions_serial
        self.build_extension(ext)
      File "/opt/conda/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 202, in build_extension
        _build_ext.build_extension(self, ext)
      File "/opt/conda/lib/python3.9/distutils/command/build_ext.py", line 529, in build_extension
        objects = self.compiler.compile(sources,
      File "/opt/conda/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 649, in unix_wrap_ninja_compile
        cuda_post_cflags = unix_cuda_flags(cuda_post_cflags)
      File "/opt/conda/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 548, in unix_cuda_flags
        cflags + _get_cuda_arch_flags(cflags))
      File "/opt/conda/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1780, in _get_cuda_arch_flags
        arch_list[-1] += '+PTX'
    IndexError: list index out of range
    ----------------------------------------
ERROR: Command errored out with exit status 1: /opt/conda/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/pillarnext/setup.py'"'"'; __file__='"'"'/home/pillarnext/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
root@453cd795ecb9:/home/pillarnext# pip install -v -e . 
Using pip 21.2.4 from /opt/conda/lib/python3.9/site-packages/pip (python 3.9)
Obtaining file:///home/pillarnext
    Running command python setup.py egg_info
    No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
    running egg_info
    creating /tmp/pip-pip-egg-info-za95g8wj/det3d.egg-info
    writing /tmp/pip-pip-egg-info-za95g8wj/det3d.egg-info/PKG-INFO
    writing dependency_links to /tmp/pip-pip-egg-info-za95g8wj/det3d.egg-info/dependency_links.txt
    writing top-level names to /tmp/pip-pip-egg-info-za95g8wj/det3d.egg-info/top_level.txt
    writing manifest file '/tmp/pip-pip-egg-info-za95g8wj/det3d.egg-info/SOURCES.txt'
    reading manifest file '/tmp/pip-pip-egg-info-za95g8wj/det3d.egg-info/SOURCES.txt'
    adding license file 'LICENSE'
    writing manifest file '/tmp/pip-pip-egg-info-za95g8wj/det3d.egg-info/SOURCES.txt'
Installing collected packages: det3d
  Running setup.py develop for det3d
    Running command /opt/conda/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/pillarnext/setup.py'"'"'; __file__='"'"'/home/pillarnext/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
    No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
    running develop
    running egg_info
    writing det3d.egg-info/PKG-INFO
    writing dependency_links to det3d.egg-info/dependency_links.txt
    writing top-level names to det3d.egg-info/top_level.txt
    reading manifest file 'det3d.egg-info/SOURCES.txt'
    adding license file 'LICENSE'
    writing manifest file 'det3d.egg-info/SOURCES.txt'
    running build_ext
    building 'det3d.core.iou3d_nms.iou3d_nms_cuda' extension
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/pillarnext/setup.py", line 18, in <module>
        setup(
      File "/opt/conda/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/opt/conda/lib/python3.9/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/opt/conda/lib/python3.9/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/opt/conda/lib/python3.9/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/opt/conda/lib/python3.9/site-packages/setuptools/command/develop.py", line 34, in run
        self.install_for_development()
      File "/opt/conda/lib/python3.9/site-packages/setuptools/command/develop.py", line 114, in install_for_development
        self.run_command('build_ext')
      File "/opt/conda/lib/python3.9/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/opt/conda/lib/python3.9/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/opt/conda/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 79, in run
        _build_ext.run(self)
      File "/opt/conda/lib/python3.9/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
        _build_ext.build_ext.run(self)
      File "/opt/conda/lib/python3.9/distutils/command/build_ext.py", line 340, in run
        self.build_extensions()
      File "/opt/conda/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 843, in build_extensions
        build_ext.build_extensions(self)
      File "/opt/conda/lib/python3.9/site-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
        _build_ext.build_ext.build_extensions(self)
      File "/opt/conda/lib/python3.9/distutils/command/build_ext.py", line 449, in build_extensions
        self._build_extensions_serial()
      File "/opt/conda/lib/python3.9/distutils/command/build_ext.py", line 474, in _build_extensions_serial
        self.build_extension(ext)
      File "/opt/conda/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 202, in build_extension
        _build_ext.build_extension(self, ext)
      File "/opt/conda/lib/python3.9/distutils/command/build_ext.py", line 529, in build_extension
        objects = self.compiler.compile(sources,
      File "/opt/conda/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 649, in unix_wrap_ninja_compile
        cuda_post_cflags = unix_cuda_flags(cuda_post_cflags)
      File "/opt/conda/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 548, in unix_cuda_flags
        cflags + _get_cuda_arch_flags(cflags))
      File "/opt/conda/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1780, in _get_cuda_arch_flags
        arch_list[-1] += '+PTX'
    IndexError: list index out of range
ERROR: Command errored out with exit status 1: /opt/conda/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/pillarnext/setup.py'"'"'; __file__='"'"'/home/pillarnext/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.

**Comment by MAI-KOKO** [comment]
root@453cd795ecb9:/home/pillarnext# pip install -e .
Obtaining file:///home/pillarnext
Installing collected packages: det3d
  Running setup.py develop for det3d
    ERROR: Command errored out with exit status 1:
     command: /opt/conda/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/pillarnext/setup.py'"'"'; __file__='"'"'/home/pillarnext/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: /home/pillarnext/
    Complete output (56 lines):
    No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
    running develop
    running egg_info
    writing det3d.egg-info/PKG-INFO
    writing dependency_links to det3d.egg-info/dependency_links.txt
    writing top-level names to det3d.egg-info/top_level.txt
    reading manifest file 'det3d.egg-info/SOURCES.txt'
    adding license file 'LICENSE'
    writing manifest file 'det3d.egg-info/SOURCES.txt'
    running build_ext
    building 'det3d.core.iou3d_nms.iou3d_nms_cuda' extension
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/pillarnext/setup.py", line 18, in <module>
        setup(
      File "/opt/conda/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/opt/conda/lib/python3.9/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/opt/conda/lib/python3.9/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/opt/conda/lib/python3.9/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/opt/conda/lib/python3.9/site-packages/setuptools/command/develop.py", line 34, in run
        self.install_for_development()
      File "/opt/conda/lib/python3.9/site-packages/setuptools/command/develop.py", line 114, in install_for_development
        self.run_command('build_ext')
      File "/opt/conda/lib/python3.9/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/opt/conda/lib/python3.9/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/opt/conda/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 79, in run
        _build_ext.run(self)
      File "/opt/conda/lib/python3.9/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
        _build_ext.build_ext.run(self)
      File "/opt/conda/lib/python3.9/distutils/command/build_ext.py", line 340, in run
        self.build_extensions()
      File "/opt/conda/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 843, in build_extensions
        build_ext.build_extensions(self)
      File "/opt/conda/lib/python3.9/site-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
        _build_ext.build_ext.build_extensions(self)
      File "/opt/conda/lib/python3.9/distutils/command/build_ext.py", line 449, in build_extensions
        self._build_extensions_serial()
      File "/opt/conda/lib/python3.9/distutils/command/build_ext.py", line 474, in _build_extensions_serial
        self.build_extension(ext)
      File "/opt/conda/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 202, in build_extension
        _build_ext.build_extension(self, ext)
      File "/opt/conda/lib/python3.9/distutils/command/build_ext.py", line 529, in build_extension
        objects = self.compiler.compile(sources,
      File "/opt/conda/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 649, in unix_wrap_ninja_compile
        cuda_post_cflags = unix_cuda_flags(cuda_post_cflags)
      File "/opt/conda/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 548, in unix_cuda_flags
        cflags + _get_cuda_arch_flags(cflags))
      File "/opt/conda/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1780, in _get_cuda_arch_flags
        arch_list[-1] += '+PTX'
    IndexError: list index out of range
    ----------------------------------------
ERROR: Command errored out with exit status 1: /opt/conda/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/pillarnext/setup.py'"'"'; __file__='"'"'/home/pillarnext/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
root@453cd795ecb9:/home/pillarnext# pip install -v -e . 
Using pip 21.2.4 from /opt/conda/lib/python3.9/site-packages/pip (python 3.9)
Obtaining file:///home/pillarnext
    Running command python setup.py egg_info
    No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
    running egg_info
    creating /tmp/pip-pip-egg-info-za95g8wj/det3d.egg-info
    writing /tmp/pip-pip-egg-info-za95g8wj/det3d.egg-info/PKG-INFO
    writing dependency_links to /tmp/pip-pip-egg-info-za95g8wj/det3d.egg-info/dependency_links.txt
    writing top-level names to /tmp/pip-pip-egg-info-za95g8wj/det3d.egg-info/top_level.txt
    writing manifest file '/tmp/pip-pip-egg-info-za95g8wj/det3d.egg-info/SOURCES.txt'
    reading manifest file '/tmp/pip-pip-egg-info-za95g8wj/det3d.egg-info/SOURCES.txt'
    adding license file 'LICENSE'
    writing manifest file '/tmp/pip-pip-egg-info-za95g8wj/det3d.egg-info/SOURCES.txt'
Installing collected packages: det3d
  Running setup.py develop for det3d
    Running command /opt/conda/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/pillarnext/setup.py'"'"'; __file__='"'"'/home/pillarnext/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
    No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
    running develop
    running egg_info
    writing det3d.egg-info/PKG-INFO
    writing dependency_links to det3d.egg-info/dependency_links.txt
    writing top-level names to det3d.egg-info/top_level.txt
    reading manifest file 'det3d.egg-info/SOURCES.txt'
    adding license file 'LICENSE'
    writing manifest file 'det3d.egg-info/SOURCES.txt'
    running build_ext
    building 'det3d.core.iou3d_nms.iou3d_nms_cuda' extension
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/pillarnext/setup.py", line 18, in <module>
        setup(
      File "/opt/conda/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/opt/conda/lib/python3.9/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/opt/conda/lib/python3.9/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/opt/conda/lib/python3.9/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/opt/conda/lib/python3.9/site-packages/setuptools/command/develop.py", line 34, in run
        self.install_for_development()
      File "/opt/conda/lib/python3.9/site-packages/setuptools/command/develop.py", line 114, in install_for_development
        self.run_command('build_ext')
      File "/opt/conda/lib/python3.9/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/opt/conda/lib/python3.9/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/opt/conda/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 79, in run
        _build_ext.run(self)
      File "/opt/conda/lib/python3.9/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
        _build_ext.build_ext.run(self)
      File "/opt/conda/lib/python3.9/distutils/command/build_ext.py", line 340, in run
        self.build_extensions()
      File "/opt/conda/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 843, in build_extensions
        build_ext.build_extensions(self)
      File "/opt/conda/lib/python3.9/site-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
        _build_ext.build_ext.build_extensions(self)
      File "/opt/conda/lib/python3.9/distutils/command/build_ext.py", line 449, in build_extensions
        self._build_extensions_serial()
      File "/opt/conda/lib/python3.9/distutils/command/build_ext.py", line 474, in _build_extensions_serial
        self.build_extension(ext)
      File "/opt/conda/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 202, in build_extension
        _build_ext.build_extension(self, ext)
      File "/opt/conda/lib/python3.9/distutils/command/build_ext.py", line 529, in build_extension
        objects = self.compiler.compile(sources,
      File "/opt/conda/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 649, in unix_wrap_ninja_compile
        cuda_post_cflags = unix_cuda_flags(cuda_post_cflags)
      File "/opt/conda/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 548, in unix_cuda_flags
        cflags + _get_cuda_arch_flags(cflags))
      File "/opt/conda/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1780, in _get_cuda_arch_flags
        arch_list[-1] += '+PTX'
    IndexError: list index out of range
ERROR: Command errored out with exit status 1: /opt/conda/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/pillarnext/setup.py'"'"'; __file__='"'"'/home/pillarnext/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.

**Comment by Konstantin5389** [comment]
according to "No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'"
it seems like that your container has no available gpu or cuda. Please use our docker image or use --gpus all when run docker
